[theme]
primaryColor = "#1E90FF"           # A deep blue for a professional feel
backgroundColor = "#F5F5F5"        # Light gray for a clean, minimalistic background
secondaryBackgroundColor = "#E0E0E0"  # Slightly darker gray for secondary elements
textColor = "#333333"              # Dark gray for readability
font = "sans serif"                # Clean, modern font
